### ISSUE TITLE
BTrees (unittest.loader._FailedTest) ... ERROR

### ISSUE THREAD

**Issue by samrose** [flyingcircusio/vulnix#39] opened 2018-06-28 14:12 UTC
Installing vulnix 1.6.3 from nixpkgs unstable results in

```
BTrees (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: BTrees (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: BTrees
Traceback (most recent call last):
  File "/nix/store/pz8nl4cnppd3p1cykshcb40mqxjd5yvy-python3-3.6.5/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/tmp/nix-build-python3.6-BTrees-4.5.0.drv-0/BTrees-4.5.0/BTrees/__init__.py", line 15, in <module>
    import zope.interface
ModuleNotFoundError: No module named 'zope.interface'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=1 errors=1 failures=0>
builder for '/nix/store/8k0s96ryc03lsam80f9fr8wwgasd97n4-python3.6-BTrees-4.5.0.drv' failed with exit code 1
cannot build derivation '/nix/store/liykw3g2crwj4mvzzqv73khvs4xik0p4-python3.6-ZODB-5.4.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/3bcipza729hy5jamyhxrlx30z02w9nkv-vulnix-1.6.3.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3bcipza729hy5jamyhxrlx30z02w9nkv-vulnix-1.6.3.drv' failed
```

**Comment by adisbladis** [comment] 2018-06-28 15:28
It works on current master.
I fixed another issue with `btrees` earlier today in https://github.com/nixos/nixpkgs/commit/7c96b917a5b174eebd58bd1e297e747875a8bda1.

Once unstable progresses past that commit `vulnix` should work again.

**Comment by ckauhaus** [comment] 2018-07-02 19:43
This was an upstream build failure not directly caused by vulnix. The build has been fixed in the meanwhile. vulnix is building correctly again.

**Closed by ckauhaus** 2018-07-02 19:43 UTC
